import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const myFont = localFont({
  src: "./../public/fonts/Yekan.woff",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: {children: React.ReactNode;}) {

  

  return (
    <html lang="en" dir="rtl" className={myFont.className}>
      {/* <body className={inter.className}>{children}</body> */}
      <body>{children}</body>
    </html>
  );
}
